### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by Demoli** [Skywire/cz-conventional-changelog#3]
The tests they are a failing.

Maybe move them to GH actions if we don't intend to merge any of this back into the main trunk.

**Comment by edward-simpson** [comment]
Doesn't look like any of our commits have passing tests

**Comment by Demoli** [comment]
@davidalexander I see we've removed the issues and issuesList from our changelog, is that correct?

**Comment by davidalexander** [comment]
@Demoli Not sure what those two elements are?

**Comment by Demoli** [comment]
Looks like it may be a list of repository issue numbers affected / fixed by the commit.
Also notice that breaking change has been removed.

**Comment by davidalexander** [comment]
Ah, with you. Yes issues and issuesList were deliberately removed.

**Comment by Demoli** [comment]
Tests updated to remove issues and breaking changes, added DD# check, updated readme badges.
